[package]
name = "subscriber"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "0.9.3"
borsh-derive = "0.9.1"
crosstown_bus = "0.5.3"
tokio = {version="1.21.2", features=["full"]}
futures = "0.3"
